// import { default as UpRatingIcon } from './18_up_rating-48px.svg'
// import AddIcon from './add-48px.svg'
// import AddToFavoriteIcon from './add_to_favorite-48px.svg'
// import ArrowBackIcon from './arrow_back-48px.svg'
// import BookmarksIcon from './bookmarks-48px.svg'
// import CalendarMonthIcon from './calendar_month-48px.svg'
// import CategoryIcon from './category-48px.svg'
// import CheckIcon from './check-48px.svg'
// import ChevronRightIcon from './chevron_right-48px.svg'
// import CloseIcon from './close-48px.svg'
// import DeleteIcon from './delete-48px.svg'
export { default as DownloadIcon } from './download-48px.svg'
// import EditIcon from './edit-48px.svg'
export { default as ExpandMoreIcon } from './expand_more-48px.svg'
// import FastForwardIcon from './fast_forward-48px.svg'
// import FastRewindIcon from './fast_rewind-48px.svg'
// import FeedbackIcon from './feedback-48px.svg'
// import FilterListIcon from './filter_list-48px.svg'
// import FilterListOffIcon from './filter_list_off-48px.svg'
// import FlagIcon from './flag-48px.svg'
// import HlsIcon from './hls-48px.svg'
// import HomeIcon from './home-48px.svg'
// import VoiceIcon from './keyboard_voice-48px.svg'
// import Kp3dIcon from './kp_3d.svg'
// import KpImaxIcon from './kp_imax.svg'
// import KpTop250LIcon from './kp_top_250_left.svg'
// import KpTop250RIcon from './kp_top_250_right.svg'
// import MenuIcon from './menu-48px.svg'
// import PauseIcon from './pause-48px.svg'
// import PlayIcon from './play_arrow-48px.svg'
// import RefreshIcon from './refresh-48px.svg'
// import RemoveFromFavoriteIcon from './remove_from_favorite-48px.svg'
// import SearchIcon from './search-48px.svg'
// import SettingsIcon from './settings-48px.svg'
// import NextIcon from './skip_next-48px.svg'
// import PrevIcon from './skip_prev-48px.svg'
// import SortIcon from './sort-48px.svg'
// import StarIcon from './star-48px.svg'
// import SubscriptionsIcon from './subscriptions-48px.svg'
// import SubtitlesIcon from './subtitles-48px.svg'
// import TheaterComedyIcon from './theater_comedy-48px.svg'
// import UpgradeIcon from './upgrade-48px.svg'
// import LibraryIcon from './video_library-48px.svg'
// import VisibilityIcon from './visibility-48px.svg'
// import VisibilityOffIcon from './visibility_off-48px.svg'
// import WallpaperIcon from './wallpaper-48px.svg'

// export { AddIcon, AddToFavoriteIcon, ArrowBackIcon, BookmarksIcon, CalendarMonthIcon, CategoryIcon, CheckIcon, ChevronRightIcon, CloseIcon, DeleteIcon, DownloadIcon, EditIcon, ExpandMoreIcon, FastForwardIcon, FastRewindIcon, FeedbackIcon, FilterListIcon, FilterListOffIcon, FlagIcon, HlsIcon, HomeIcon, Kp3dIcon, KpImaxIcon, KpTop250LIcon, KpTop250RIcon, LibraryIcon, MenuIcon, NextIcon, PauseIcon, PlayIcon, PrevIcon, RefreshIcon, RemoveFromFavoriteIcon, SearchIcon, SettingsIcon, SortIcon, StarIcon, SubscriptionsIcon, SubtitlesIcon, TheaterComedyIcon, UpRatingIcon, UpgradeIcon, VisibilityIcon, VisibilityOffIcon, VoiceIcon, WallpaperIcon }
